import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import Footer from "../../components/moleculas/Footer/Footer";
import Header from "../../components/moleculas/Header/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Despertar para a ciência",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="en">
      <Header />
      <div className={`${montserrat.className} antialiased`}>{children}</div>
      <Footer />
    </div>
  );
}
